// Get all data from API and render to table
$(() => {
    axios.get('https://cukcuk.manhnv.net/api/v1/Employees')
        .then((response) => {
            var data = response.data;
            var container = $('#data-container');
            container.empty(); // Clear any existing rows

            data.forEach((item, index) =>  {
                var row = `
                    <tr class="app__content-table-row">
                        <td class="app__content-table-cell">${index + 1}</td>
                        <td class="app__content-table-cell">${item.EmployeeCode}</td>
                        <td class="app__content-table-cell">${item.FullName}</td>
                        <td class="app__content-table-cell">${item.Gender}</td>
                        <td class="app__content-table-cell">${item.Gender}</td>
                        <td class="app__content-table-cell">${item.Email}</td>
                        <td class="app__content-table-cell">${item.Address}</td>
                        <td class="app__content-table-cell">
                            <div class="app__content-table-cell-action">
                                <img class="app__content-table-cell-action-img" src="/resources/assets/icon/edit.png" alt="Edit">
                                <img class="app__content-table-cell-action-img" src="/resources/assets/icon/delete-48.png" alt="Delete">
                            </div>
                        </td>
                    </tr>`;
                container.append(row);
            });
        })
        .catch((error) => {
            console.error('Error fetching data:', error);
            $('#data-container').append('<tr><td colspan="9">Error fetching data. Please try again later.</td></tr>');
        });
});

// Search employee by key
$(() => {
    $('#search-button').click(() => {
        var keyword = $('#search-input').val();
        searchEmployees(keyword);
    });
});

function searchEmployees(keyword) {
    axios.get(`https://cukcuk.manhnv.net/api/v1/Employees/filter?employeeFilter=${keyword}`, {
        params: {
            search: keyword
        }
    })
    .then((response) => {
        var data = response.data;
        var container = $('#data-container');
        container.empty(); // Clear any existing rows

        console.log(data);

        data.Data.forEach((item, index) => {
            var row = `
                <tr class="app__content-table-row">
                    <td class="app__content-table-cell">${index + 1}</td>
                    <td class="app__content-table-cell">${item.EmployeeCode}</td>
                    <td class="app__content-table-cell">${item.FullName}</td>
                    <td class="app__content-table-cell">${item.Gender}</td>
                    <td class="app__content-table-cell">${item.Gender}</td>
                    <td class="app__content-table-cell">${item.Email}</td>
                    <td class="app__content-table-cell">${item.Address}</td>
                    <td class="app__content-table-cell">
                        <div class="app__content-table-cell-action">
                            <img class="app__content-table-cell-action-img" src="/resources/assets/icon/edit.png" alt="Edit">
                            <img class="app__content-table-cell-action-img" src="/resources/assets/icon/delete-48.png" alt="Delete">
                        </div>
                    </td>
                </tr>`;
            container.append(row);
        });
    })
    .catch((error) => {
        console.error('Error fetching data:', error);
        $('#data-container').append('<tr><td colspan="8">Error fetching data. Please try again later.</td></tr>');
    });
}

// Add new employee
$(() => {
    $('#add-button').click(() => {
        addEmployee();
    });
});

function addEmployee() {
    var newEmployee = {
        createdDate: new Date().toISOString(),
        createdBy: "admin",
        modifiedDate: new Date().toISOString(),
        modifiedBy: "admin",
        employeeId: "3fa85f64-5717-4562-b3fc-2c963f66afa6", // Ideally, this should be generated by the server
        employeeCode: "NV1234",
        firstName: "Nguyen",
        lastName: "Van A",
        fullName: "Nguyen Van A",
        gender: 0,
        dateOfBirth: new Date().toISOString(),
        phoneNumber: "0901234567",
        email: "nguyenvana@example.com",
        address: "123 Main Street",
        identityNumber: "123456789",
        identityDate: new Date().toISOString(),
        identityPlace: "Hanoi",
        joinDate: new Date().toISOString(),
        martialStatus: 0,
        educationalBackground: 0,
        qualificationId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        departmentId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        positionId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        nationalityId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        workStatus: 0,
        personalTaxCode: "123456789",
        salary: 5000000,
        positionCode: "DEV",
        positionName: "Developer",
        departmentCode: "IT",
        departmentName: "Information Technology",
        qualificationName: "Bachelor",
        nationalityName: "Vietnamese"
    };

    axios.post('https://cukcuk.manhnv.net/api/v1/Employees', newEmployee)
        .then((response) => {
            console.log('Employee added successfully:', response.data);
            alert('Employee added successfully!');
        })
        .catch((error) => {
            console.error('Error adding employee:', error);
            alert('Error adding employee. Please try again.');
        });
}